# Spring boot application
spring:
  application:
    name: dubbo-provider-demo
server:
  port: 9090
management:
  port: 9091

# Base packages to scan Dubbo Components (e.g., @Service, @Reference)
dubbo:
  scan:
    basePackages: com.xanthuim.service
  # Dubbo Config properties
  ## ApplicationConfig Bean
  application:
    id: dubbo-provider-demo
    name: dubbo-provider-demo
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
  ## RegistryConfig Bean
  registry:
    id: my-registry
    address: zookeeper://172.16.136.236:2181