# 在这里编写springboot的配置信息
server:
  port: 8080
  context-path: /
  application:
    name: dubbo-consumer-demo

management:
  port: 8081


# Dubbo Config properties
## ApplicationConfig Bean
dubbo:
  application:
    id: dubbo-consumer-demo
    name: dubbo-consumer-demo
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
  ## RegistryConfig Bean
  registry:
    id: my-registry
    address: zookeeper://172.16.136.236:2181

